# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 发送ping的post请求
POST http://127.0.0.1:3000/api/v1/ping
Content-Type: application/json

### 创建视频的post请求
POST http://127.0.0.1:3000 /api/v1/videos
Content-Type: application/json

{
  "title": "第二个视频",
  "info": "two xxxxx"
}

### 获取视频
GET http://127.0.0.1:3000/api/v1/video/1

### 获取视频列表
GET http://127.0.0.1:3000/api/v1/videos

### 修改视频
PUT http://127.0.0.1:3000/api/v1/video/1
Content-Type: application/json

{
  "title": "第1个视频",
  "info": "two xxxxx"
}

### 删除视频
DELETE http://127.0.0.1:3000/api/v1/video/1

###
